services:
  - type: web
    name: replytics-dashboard-api
    runtime: python
    rootDir: backend
    buildCommand: ./render-build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: VOICE_BOT_URL
        value: https://replytics-dhhf.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
    healthCheckPath: /health
    autoDeploy: true
