# Prometheus Configuration - Production
# /Users/jakespringer/Desktop/Replytics Website/config/prometheus.production.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'replytics-prod-monitor'
    environment: 'production'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Frontend Next.js Application
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_timestamps: true
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'nodejs_.*'
        target_label: 'service'
        replacement: 'frontend'

  # Voice-Bot Backend
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_timestamps: true
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'voice_bot_.*'
        target_label: 'service'
        replacement: 'voice-bot'

  # Nginx Load Balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s
    scrape_timeout: 5s

  # Duckling NLP Service
  - job_name: 'duckling'
    static_configs:
      - targets: ['duckling:8000']
    metrics_path: '/metrics'
    scrape_interval: 60s
    scrape_timeout: 10s

  # System metrics (if node_exporter is available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Container metrics (if cadvisor is available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s
    metric_relabel_configs:
      - source_labels: [container_label_com_docker_compose_service]
        target_label: 'service'
      - source_labels: [container_label_com_docker_compose_project]
        target_label: 'project'

  # Health checks
  - job_name: 'health-checks'
    metrics_path: '/probe'
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://frontend:3000/api/health
        - http://backend:8000/health
        - http://nginx:80/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115