apiVersion: v1
kind: ServiceAccount
metadata:
  name: replytics-frontend
  namespace: production
  labels:
    app: replytics-frontend
    environment: production
  annotations:
    eks.amazonaws.com/role-arn: "${AWS_ROLE_ARN}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: replytics-frontend-role
  labels:
    app: replytics-frontend
    environment: production
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: replytics-frontend-rolebinding
  namespace: production
  labels:
    app: replytics-frontend
    environment: production
subjects:
- kind: ServiceAccount
  name: replytics-frontend
  namespace: production
roleRef:
  kind: Role
  name: replytics-frontend-role
  apiGroup: rbac.authorization.k8s.io